# Generated by Django 2.2 on 2022-07-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_no', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'CLIENT',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('state_ut', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'DEALER',
            },
        ),
        migrations.CreateModel(
            name='Oem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'OEM',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'SPECIFICATION',
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=100)),
                ('battery_type', models.CharField(max_length=50)),
                ('short_cell_description', models.CharField(max_length=150)),
                ('long_cell_description', models.CharField(max_length=250)),
                ('bms_specification', models.CharField(max_length=100)),
                ('cell_brand', models.CharField(max_length=100)),
                ('matal_case_specification', models.CharField(max_length=100)),
                ('nickel_specification', models.CharField(max_length=100)),
                ('nickel_weight', models.CharField(max_length=50)),
                ('nominal_voltage', models.CharField(max_length=50)),
                ('nominal_capacity', models.CharField(max_length=50)),
                ('oem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.Oem')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.Specification')),
            ],
            options={
                'verbose_name_plural': 'BATTERY',
            },
        ),
    ]
